import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <h1 className="text-5xl pl-4 flex justify-center text-green-800 pt-4 mt-4">PLATAFORMA DE REGISTRO</h1>
       <main className="container mx-auto px-5 mt-4">
       {children}
       </main>
      </body>
    </html>
  );
}
